name: hello_world
description: Hello world

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_flavorizr:
    git:
      url: https://github.com/tungtd95/flutter_flavorizr.git
      ref: v2.2.0

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:

  flavors:
    dev:
      app:
        name: "Weather Dev"

      android:
        applicationId: "com.sekiroflutter.helloiap.dev"

      ios:
        bundleId: "com.sekiroflutter.helloiap.dev"

    prod:
      app:
        name: "Weather"

      android:
        applicationId: "com.sekiroflutter.helloiap"

      ios:
        bundleId: "com.sekiroflutter.helloiap"
